# creating namespace 
apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: null
  name: ashu-jk-deploy # change this part 
spec: {}
status: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: ashu-webapp
  name: ashu-webapp # name of deployment 
  namespace: ashu-jk-deploy # add namespace 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ashu-webapp
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels: # check label of pods
        app: ashu-webapp
    spec:
      containers:
      - image: dockerashu/ashu-cloud4c-app:version23 # change docker with your image 
        name: ashu-cloud4c-app
        ports:
        - containerPort: 80
        resources: {}
status: {}

# creating nodeport service
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: ashulb1
  name: ashulb1 # change name 
  namespace: ashu-jk-deploy # add this 
spec:
  ports:
  - name: 1234-80
    port: 1234
    protocol: TCP
    targetPort: 80
  selector: # selector also 
   app: ashu-webapp # label 
  type: NodePort
status:
  loadBalancer: {}
